title: nanvc
description: A focused TypeScript client for the HashiCorp Vault HTTP API
url: "https://zailic.github.io"
markdown: kramdown
permalink: pretty
baseurl: "/nanvc"

header_pages:
  - index.md
  - getting-started.md
  - examples.md
  - api-v1.md
  - api-v2.md
  - error-handling.md
  - changelog.md
  - contributing.md

plugins:
  - jekyll-feed

defaults:
  - scope:
      path: ""
    values:
      layout: page

highlighter: rouge
