name: CI

on:
  - push
  - pull_request

jobs:
  
  test:

    name: Testing NANVC library through nodejs v${{ matrix.node-version }}.x on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        node-version:
          - 16
#          - 14
        os:
          - ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Build the containers stack
        run: docker-compose up -d
      - name: Adding host aliases  
        run: echo "127.0.0.1 vault.local" | sudo tee -a /etc/hosts
      - name: Install nodejs dependencies
        run: npm install
      - name: Run testing suite  
        run: npm run coverage
      - name: Coveralls  
        uses: codecov/codecov-action@v1
        if: matrix.os == 'ubuntu-latest' && matrix.node-version == 16
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          fail_ci_if_error: true
