name: NPM publish

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.release.target_commitish }}
      - name: Use nodejs v14
        uses: actions/setup-node@v2
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org/
      - name: Build the containers stack (integration tests dependency)
        run: docker-compose up -d
      - name: Adding host aliases (integration tests requirement)  
        run: echo "127.0.0.1 vault.local" | sudo tee -a /etc/hosts
      - name: Install nodejs dependencies
        run: npm install
      - name: Run tests
        run: npm run test:all
      - name: Build the package
        run: npm run build
      - run: npm publish
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}